### ISSUE TITLE
Where to get the SDK

### ISSUE THREAD

**Issue by alexeygolev** [YuzukiHD/R128Module#2]
Thank you for collecting the tools and the docs in a nice convenient format. Unfortunately it's not clear where one gets the R128 SDK. I asked on aw-ol.com but the response was "the SDK is not ready". In your docs it says "stay tuned". I'm finding more and more projects describing how to use R128 but it's not possible to use it without the SDK.

I assume I'm looking at the wrong place. Please assist

**Comment by bhgv** [comment]
aw r128 SDK v0.9:

https://github.com/bhgv/Allwinner-R128S2-SDK-09
